### ISSUE TITLE
Duplicate `--help` options in command line parser

### ISSUE THREAD

**Issue by Gabriel439** [haskell/criterion#168]
The motivation for this is the following issue:

https://github.com/Gabriel439/bench/issues/18

The `criterion` command line parser (which `bench` uses) generates a large number of duplicate options and I believe it's (sort of) due to the following commit:

https://github.com/bos/criterion/commit/07ea59021549e95756f9807f5728045cb0a76c40#diff-9c99903e0c43363e8717671631af65fa

The issue appears to be that the `config` parser is used once for both the `Run` and `RunIters` alternatives instead of used once and shared between the two alternatives.  This means that all the options that the `config` parser requires appear twice in the `--help` output

**Comment by RyanGlScott** [comment]
Thanks for the bug report! I've uploaded [`criterion-1.2.4.0`](http://hackage.haskell.org/package/criterion-1.2.4.0) to Hackage with a fix.

**Comment by Gabriel439** [comment]
You're welcome and thank you!

**Comment by RyanGlScott** [comment]
Actually, it turns out that this issue wasn't entirely fixed, since the `--match` option still appears twice in the `--help` output:

```
Usage: fibber <snip>
              [[-m|--match MATCH] [NAME...] | (-n|--iters ITERS) 
                [-m|--match MATCH] [NAME...] |
                (-l|--list) | --version]

Available options:
  <snip>
  -m,--match MATCH         How to match benchmark names ("prefix", "glob",
                           "pattern", or "ipattern")
  -n,--iters ITERS         Run benchmarks, don't analyse
  -m,--match MATCH         How to match benchmark names ("prefix", "glob",
                           "pattern", or "ipattern")
  -l,--list                List benchmarks
  --version                Show version info
```

This is because the `Parser` for match appears on both sides of an `(<|>)` expression [here](https://github.com/haskell/criterion/blob/dd778bcb2df14592a63df3f2ae945dca021d4bc4/Criterion/Main/Options.hs#L106-L107). I wonder if perhaps `optparse-applicative` should be responsible for deduplicating `--help` text in situations like this. In any case, I think the most direct fix would be to factor the `--match` parser outside of the `(<|>)`. This would make the resulting code slightly more indirect, but I'd argue that the pros would outweigh the cons in this case.
