### ISSUE TITLE
[FR] support benchmarking max memory usage

### ISSUE THREAD

**Issue by NightMachinary** [haskell/criterion#256]
Migrated from https://github.com/Gabriel439/bench/issues/45#issuecomment-1014904269 .

**Comment by RyanGlScott** [comment]
A place to start would be to record the [`max_mem_in_use_bytes`](https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-Stats.html#v:max_mem_in_use_bytes) from the `RTSStats` in the [`getStatistics`](https://github.com/haskell/criterion/blob/3f6a32b01dbadb5c0954aaebaf4fef923e7ac7ec/criterion-measurement/src/Criterion/Measurement.hs#L121) function. Then you'd need to update the maximum in the [`addResults`](https://github.com/haskell/criterion/blob/3f6a32b01dbadb5c0954aaebaf4fef923e7ac7ec/criterion-measurement/src/Criterion/Measurement.hs#L219) function. (If we start recording maximum values, however, the name `addResults` isn't really accurate anymore, since you wouldn't add two maximum values together.)

**Comment by RyanGlScott** [comment]
Thanks for working on this, @tbidne! Please do open a PR, as it would be more convenient to review the patch using the GitHub review UI. From a quick glance, your patch looks like what I was imagining it would be.

**Comment by RyanGlScott** [comment]
Fixed in #260.
