### ISSUE TITLE
Update tutorial to suggest `v2-`style `cabal` commands

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/criterion#267]
Currently, the `criterion` tutorial recommends installing `criterion` using `v1-install`:

https://github.com/haskell/criterion/blob/4d6bd209bc72172c540610182f3f01b688e62e55/www/tutorial.md?plain=1#L6-L12

This should be updated to suggest `v2-`style commands instead.

**Comment by BELLEbanna** [comment]
1 @ 4d6bd20
2  "cabal"  is the standard Haskell 
3 criterion requires simple packaging for management command. 
4 please meet me halfway (VERIZON 3.0) at 12.5 probability 
5 code can be found in all walks of EARTH
6 Feeling like I'm falling because I AM ALIENATED 
7 Freak show circus performer
8 ALL GAWK @ this peacock
9 FROZEN 
10 THAW to flee
11 ESCAPE "FINDING DORY"
12 Dorthe from the Wizard of OZ
13 GENIe in the bottle grant me xfinity amount of wishes
14 Walt Disneyworld can be made equal for all people socialism Green Party
15 TBA
